# Generated by Django 4.2.11 on 2024-03-05 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import foods.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("name_en", models.CharField(max_length=100, verbose_name="Название на англ")),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("number", models.IntegerField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="SubMenu",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("name_en", models.CharField(max_length=100, verbose_name="Название на англ")),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("number", models.IntegerField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Foods",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("name_en", models.CharField(max_length=100, verbose_name="Название на англ")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="Описание на англ")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена")),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="PNG",
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, 500],
                        upload_to=foods.models.food_directory_path,
                        verbose_name="Фото",
                    ),
                ),
                ("weight", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="foods",
                        to="foods.categories",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="categories",
            name="sub_menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="foods.submenu"
            ),
        ),
    ]
