version: "3.9"

networks:
  default:
    name: menu-network
    external: true

volumes:
  pg-data:

services:

  postgres:
    restart: always
    container_name: menu-postgres

    image: postgres:alpine

    volumes:
      - pg-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d feedlocal" ]
      interval: 1s
      timeout: 3s
      retries: 10

    env_file:
      - .env

  backend:
    restart: always
    container_name: menu-backend

    build: .

    volumes:
      - .:/app/

    ports:
      - "8010:8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
