# Generated by Django 4.2.11 on 2024-03-05 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("timezone", models.CharField(choices=[("Europe/Kiev", "EET")], default="Europe/Kiev", null=True)),
                ("currency", models.CharField(choices=[("UAH", "₴")], default="UAH", null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("code", models.UUIDField(default=uuid.uuid4)),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                ("active", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="domains", to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientsStatistic",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(max_length=30)),
                ("date_time", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="statistic", to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientsHours",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("time_from", models.TimeField(default=datetime.time(0, 0))),
                ("time_by", models.TimeField(default=datetime.time(0, 0))),
                (
                    "day_number",
                    models.IntegerField(
                        choices=[
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                            ("7", "Sunday"),
                        ]
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hours", to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, null=True)),
                ("facebook", models.CharField(blank=True, null=True)),
                ("website", models.CharField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contact", to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientBrand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("color", models.CharField(default="", max_length=15)),
                ("background_color", models.CharField(default="", max_length=15)),
                ("categories_color", models.CharField(default="", max_length=15)),
                ("font", models.CharField(default="", max_length=30)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="brand", to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
